name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('playwright.config.js', 'package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Run unit tests
        run: npm test

      - name: Run Playwright smoke suite
        env:
          PLAYWRIGHT_JUNIT_OUTPUT_NAME: playwright-results.xml
          PLAYWRIGHT_HTML_REPORT: playwright-report
        run: npx playwright test --reporter=line,junit,html --output=test-results

      - name: Bundle Playwright HTML report
        if: always()
        run: |
          if [ -d playwright-report ]; then
            tar -czf playwright-report.tar.gz playwright-report
          fi

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-results.xml
            test-results
            playwright-report
            playwright-report.tar.gz
          if-no-files-found: ignore
